[colors.bright]
black = "#444446"
blue = "#8C78B0"
cyan = "#978BB8"
green = "#5D6597"
magenta = "#7695E2"
red = "#4A4F71"
white = "#c0c0c1"
yellow = "#737EC2"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#c0c0c1"
blue = "#8C78B0"
cyan = "#978BB8"
green = "#7695E2"
magenta = "#5D6597"
red = "#4A4F71"
white = "#444446"
yellow = "#737EC2"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#060609"
blue = "#695a84"
cyan = "#71688a"
green = "#454b71"
magenta = "#586fa9"
red = "#373b54"
white = "#828284"
yellow = "#565e91"

[colors.primary]
background = "#060609"
foreground = "#c0c0c1"

[colors.search.bar]
background = "#828284"
foreground = "#444446"

[colors.search.focused_match]
background = "CellForeground"
foreground = "CellBackground"

[colors.search.matches]
background = "#c0c0c1"
foreground = "#060609"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
